import "./globals.css";
import Script from "next/script";
import ReduxProvider from "./providers/ReduxProvider";
import AppBootstrap from "./providers/AppBootstrap";
import { Toaster } from "react-hot-toast";

export const metadata = {
    title: "Nyaya Path Legal",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ReduxProvider>
                    <AppBootstrap>
                        {children}
                        <Toaster
                            position="top-right"
                            reverseOrder={false}
                            gutter={8}
                            toastOptions={{
                                duration: 4000,
                                style: {
                                    background: "#1e1e1e",
                                    color: "#e5e7eb",
                                    border: "2px solid #3a3a3a",
                                    borderRadius: "8px",
                                    boxShadow: "0 10px 25px rgba(0,0,0,0.4)",
                                    fontSize: "14px",
                                },

                                success: {
                                    iconTheme: {
                                        primary: "#22c55e",
                                        secondary: "#1e1e1e",
                                    },
                                    style: {
                                        border: "1px solid #22c55e",
                                    },
                                },

                                error: {
                                    iconTheme: {
                                        primary: "#ef4444",
                                        secondary: "#1e1e1e",
                                    },
                                    style: {
                                        border: "1px solid #ef4444",
                                    },
                                },

                                loading: {
                                    iconTheme: {
                                        primary: "#3b82f6",
                                        secondary: "#1e1e1e",
                                    },
                                },
                            }}
                        />
                        <Script
                            src="https://checkout.razorpay.com/v1/checkout.js"
                            strategy="afterInteractive"
                        />
                    </AppBootstrap>
                </ReduxProvider>
            </body>
        </html>
    );
}
